[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Lupuss <damian.baczynski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raster = "0.0.7"
num_cpus = "1.12.0"